### ISSUE TITLE
Use prettyUrl's first letter for SiteIcon

### ISSUE THREAD

**Issue by oyiptong** [mozilla/activity-streams#268] opened 2016-03-04 23:31 UTC
Using the title as the SiteIcon url can be confusing. It usually doesn't have much to do with the site it's representing.

Consider using prettyUrl's output's first letter instead.

**Comment by pdehaan** [comment] 2016-03-04 23:50
Possible dupe of #229
Related #193 (should we be using favicons a lot more and fallbacks a lot less often?)

But yeah, the [current logic in SiteIcon.js:53](https://github.com/mozilla/activity-streams/blob/603206245c82b14f459b989a30ec9cde6fa571e8/content-src/components/SiteIcon/SiteIcon.js#L53) says:
```js
const letter = (provider_name || provider_display || title || "")[0];
```

So if we're always falling back to using the `title`, something has gone horribly wrong.

**Comment by pdehaan** [comment] 2016-03-08 01:23
Bryan gave some guidance for this in https://github.com/mozilla/activity-streams/issues/248#issuecomment-193450974:

> _"Replacement fav icons should use the first letter of the sub-domain if applicable, or the first letter of the domain name. In this example "C" is the first letter of the sub-domain."_

Here's a recent example of a random page I tripped over which had no favicon data (in the places db or from Embedly proxy):

![new_tab_and_siteicon_js_ _activity-streams](https://cloud.githubusercontent.com/assets/557895/13588895/81462fa0-e488-11e5-9116-cb167ce9c2a4.png)

It also makes me think our SiteIcon letter logic is slightly backwards. Currently we're using:
`provider_name` => `provider_display` => `title`

But per Bryan's suggestions, we should probably reverse the first two so it's `provider_display` => `provider_name` since the above screenshot shows the following data:

- `provider_display`: "i.puthtml.com"
- `provider_name`: "Puthtml"
- `title`: "" (empty string)

So using `provider_display` first should give us the subdomain whereas the `provider_name` won't. Which explains why the fallback letter was **"P"** versus **"I"**:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13588982/3d9e0c86-e489-11e5-9722-c38516a7ec5e.png)

**Comment by k88hudson** [comment] 2016-03-14 16:55
This is a dupe of https://github.com/mozilla/activity-streams/issues/286

**Closed by k88hudson** 2016-03-14 16:55 UTC
Labels: Add-on UI
