### ISSUE TITLE
Need to validate data collection payload and pipeline ETL

### ISSUE THREAD

**Issue by edmoz** [mozilla/activity-streams#300] opened 2016-03-14 22:25 UTC

**Comment by edmoz** [comment] 2016-03-24 20:42
Triage: Tim was saying that Max is already analyzing payload

**Comment by mzhilyaev** [comment] 2016-03-31 16:21
Is this a duplicate of #367 ?

**Comment by tspurway** [comment] 2016-03-31 16:30
duplicate of #367

**Closed by tspurway** 2016-03-31 16:30 UTC
