### ISSUE TITLE
Sort Bookmarks by creation date

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#401] opened 2016-03-30 01:17 UTC
Ref: #400 

Bookmarks should be sorted in reverse chronological order. Currently they're sorted in ______ order, which was causing much swearing by one developer who's name starts with "k" and ends with "88hudson".

![screenshot_3_29_16__6_13_pm](https://cloud.githubusercontent.com/assets/557895/14128953/7674975c-f5da-11e5-9dd5-39070ac96602.png)

**Comment by rlr** [comment] 2016-03-30 12:38
They are sorted by bookmarked date. The problem is they display the last visited date. This is fixed in pull request #377 (issue #272). Closing.

**Closed by rlr** 2016-03-30 12:38 UTC
