### ISSUE TITLE
Improve telemetry sessions 

### ISSUE THREAD

**Issue by mzhilyaev** [mozilla/activity-streams#477] opened 2016-04-06 17:07 UTC
[edited by @k88hudson]

Updating with changes as discussed with @nchapman 

- [x] If possible, Closing the browser should be `close`, not `unfocus`
- [ ] Remove `unfocus` by switching tabs session end case
- [x] Changing the route on the front end should count as a session end and start a new session

**Comment by tspurway** [comment] 2016-04-12 18:15
works as intended, but Timeline back to Newtab must report a session ping

**Comment by pdehaan** [comment] 2016-04-28 19:58
@k88hudson Was this fixed by #596, or still work to do?

**Comment by k88hudson** [comment] 2016-04-28 20:12
@pdehaan @nchapman Unfortunately I couldn't resolve "Remove `unfocus` by switching tabs session end case" without a major refactor, so I'm going to file that as a new issue.

**Closed by k88hudson** 2016-04-28 20:12 UTC
Labels: Bug, Reporting
