### ISSUE TITLE
Improve empty state/onboarding experience

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#86] opened 2016-02-10 23:30 UTC
Not sure what the what is happening, but this is probably a pretty sparse profile. But the lack of content is disorienting and makes me frightened.

![mozilla_firefox_and_new_issue_ _mozilla_activity-streams_and_reusable_components___react](https://cloud.githubusercontent.com/assets/557895/12965439/0ab43ec2-d00b-11e5-9eb3-47329c083806.png)

**Comment by pdehaan** [comment] 2016-02-10 23:40
Actually, for some reason my console is throwing a "TypeError: arguments is not iterable" error:
![mozilla_firefox_and_odd_lack_of_content_on_my_firefox_beta_ _issue__86_ _mozilla_activity-streams](https://cloud.githubusercontent.com/assets/557895/12965523/a67f2fba-d00b-11e5-87b4-0980f630a72e.png).

Clicking the stack trace begins to spiral out of control, but looking at the dev tools, it appears that it's an `eval()` statement with the contents of [/content-src/lib/ActionManager.js](https://github.com/mozilla/activity-streams/blob/master/content-src/lib/ActionManager.js). Actually, I think the screenshot is saying that it's on [line 30](https://github.com/mozilla/activity-streams/blob/9e9e50ac099d1e1437ded431f8f8a7bd63fad277/content-src/lib/ActionManager.js#L30).

**Comment by k88hudson** [comment] 2016-02-10 23:43
Agreed! Definitely not a great experience for new users :+1: 

I think this is a dupe of https://github.com/mozilla/activity-streams/issues/81, but maybe one of us can get to something super bare-bones by the end of the week

**Closed** 2016-02-12 20:55 UTC
Labels: Add-on UI
