### ISSUE TITLE
When opening the Activity Stream timeline there is a flicker for Spotlight items but no data is displayed

### ISSUE THREAD

**Issue by softvision-VladBacia** [mozilla/activity-streams#307] opened 2016-03-16 09:10 UTC
### Environment:
OS: Windows 8.1 x64 PRO
Browser: Latest Nightly (48.0a1)
User Agent: Mozilla/5.0 (Windows NT 6.3; Win64; x64; rv:48.0) Gecko/20100101 Firefox/48.0
Build ID: 20160315030230
Add-on: Activity Stream v1.0.2

### Prerequisites:
1. New profile is created.
2. Activity Stream add-on is installed.
3. Delete all history from Library (Ctrl+Shift+H)

### Steps to reproduce:
1. Visit multiple websites in order to add them to Spotlight area.
2. Click on "Activity Stream" button from browser toolbar.
3. Observe Spotlight placeholders.

### Actual results:
Empty Spotlight placeholders are displayed even if the websites were visited multiple times.
I've noticed a flicker on the Spotlight item, the data is displayed for a fraction of a second inside the Spotlight placeholder

### Expected results:
The websites that meet the criteria to be displayed in Spotlight tile, are displayed.

**Video of the issue:** 
[Spotlight flicker.zip](https://github.com/mozilla/activity-streams/files/175560/Spotlight.flicker.zip)

**Comment by tspurway** [comment] 2016-03-28 17:38
dupe of #303

**Closed by tspurway** 2016-03-28 17:38 UTC
Labels: Design feedback needed
