### ISSUE TITLE
Use tippy-top-sites as an Embedly pre-proxy?

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#444] opened 2016-04-01 21:03 UTC
Currently it looks like we're using the [**tippy-top-sites**](https://github.com/mozilla/activity-streams/search?utf8=%E2%9C%93&q=tippy-top-sites) module in 1 place, [content-test/faker.js](https://github.com/mozilla/activity-streams/blob/fc67ec4954c02f7684bcba980353e2030dadf88c/content-test/faker.js#L3), for our tests.

Since we can sometimes get suboptimal results from the Embed.ly proxy (pinterest, lowes, hackernews, etc), I'm not sure if it makes sense to try to use tippy-top-sites as a pre-proxy so we know we'll always have high quality favicons and background colors, site titles, etc, and only query embedly when necessary (such as the 99.9999% of the sites _not_ in our curated tippy-top-sites JSON).
I don't imagine there is much point in repeatedly querying youtube.com if we know we'll get back a poor quality favicon and not great titles, or whatever.

I'm sure there are several flaws with my logic (tippy-top-sites only cover top-level domains and aren't page specific, for example), so feel free to knock me down a few pegs.

Ref: #304
Ref: #384

**Comment by k88hudson** [comment] 2016-04-01 21:45
:+1:

**Comment by k88hudson** [comment] 2016-04-07 19:27
https://github.com/mozilla/activity-streams/pull/487 should land before we implement this

**Comment by oyiptong** [comment] 2016-04-07 19:40
One possible way to think about this is to have a "link pipeline", where links get decorated if there is a sequential relationship between different states.

If there are no dependencies between the different states (as it stands there isn't), we can just use the `PreviewProvider`'s main datastore as the datastore to store "rich" data, including the tippy-toppy sites.

Keep in mind that PreviewProvider's cache is ephemeral, meaning we probably want something like the decoration/pipeline approach.

**Comment by tspurway** [comment] 2016-04-18 17:32
Dupe of #384 - good additional detail here, tho...

**Comment by k88hudson** [comment] 2016-04-18 18:14
Dupe of #444

**Comment by rlr** [comment] 2016-05-03 22:52
landedededed

**Closed by rlr** 2016-05-03 22:52 UTC
Labels: Add-on APIs
