### ISSUE TITLE
Awesome bar shows resource:// URL

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#236] opened 2016-03-01 07:43 UTC
### Steps to reproduce:
1. `git clone ...` and `npm install`
2. `npm run once`
3. Click the new tab button.
4. start typing a url.

### Actual results:
URL in awesome bar is:
resource://activity-streams/data/content/activity-streams.html#/
After you start typing, it seems to append your text to the existing resource:// URL.

### Expected results:
Awesome bar should be blank. 

This used to work, so it looks like a regression of https://github.com/mozilla/activity-streams/pull/142

---

<img width="1080" alt="new_tab" src="https://cloud.githubusercontent.com/assets/557895/13420804/11814cb2-df3e-11e5-9e00-70b17bff6799.png">

**Comment by k88hudson** [comment] 2016-03-01 18:30
This is a dupe of https://github.com/mozilla/activity-streams/issues/223

**Closed by k88hudson** 2016-03-01 18:30 UTC
