### ISSUE TITLE
Block vs delete history items

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#383] opened 2016-03-30 00:17 UTC
Ref: #382 

Currently when you delete a "Top Site" or "Featured" result, it is gone forever. Maybe it's more appropriate to "block" or "hide" results from Top Sites/Featured instead of deleting the history item.

Once we do this, @pdehaan will complain he hid something "accidentally" and will demand a system to undo that action because I certainly didn't want to perma-ban all github.com/ URLs permanently.

**Comment by k88hudson** [comment] 2016-04-07 17:18
Dupe of #392

**Closed by k88hudson** 2016-04-07 17:18 UTC
Labels: Design feedback needed
