### ISSUE TITLE
Some history items not appearing in Activity Stream

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#249] opened 2016-03-02 01:20 UTC
This is... "weird".

### Steps to reproduce:
1. `$ npm run once`
2. Go to http://kinjaroundup.kinja.com/kotaku-dark-souls-3-connects-to-its-predecessors-in-som-1762214351
3. Open each of the 4 articles listed on that page in new tabs (it takes a while since some of these sites make 280 requests and push MEGABYTES of data to render some small HTML amongst the ads and tracking beacons). **Spoiler alert:** The web is gross.

### Actual results:
Only 2 of the (now 5) pages visited appear in your Activity Stream or Timeline page. On my laptop, it shows the "io9.gizmodo.com" and the original "kinjaroundup.kinja.com" pages. If I go to "History" > "Show All History", it will show my full browsing history. Also notably weird, is that we're seemingly only passing 2 URLs to our Embedly proxy (which explains why we only get 2 results back).

### Expected results:
The History window shows 5 results. I expected all those results in my Activity Stream.

---

![menubar_and_library_and_new_tab_and_embedly-proxy_dev_mozaws_net_extract_urls_http___jezebel_com_teen-girl-being-tried-for-manslaughter-after-texts-enco-1762176221_utm_source_recirculation_utm_medium_recirculation_utm_campaign_tuesdaypm_and](https://cloud.githubusercontent.com/assets/557895/13447596/bc5899a4-dfd1-11e5-8f0a-f24d45dbda8a.png)

**Comment by k88hudson** [comment] 2016-03-07 17:56
Is it possible that this is happening due to the (temporary) length filter on URLs? If so you should be seeing messages in the console (if you're in a dev build) like this:

```
"omitting https://whatever.com
because it failed test #2 of DATA_FILTERS"
```

This will be fixed when we switch over to POST style requests for embedly

**Comment by k88hudson** [comment] 2016-03-07 17:58
Ok, I just read your STR more carefully :stuck_out_tongue_winking_eye:  and tested this, I have confirmed it is due to the length restriction:

```
"omitting http://jalopnik.com/the-bugatti-lifestyle-brand-catalog-is-mega-fucking-wei-1762031616?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://kotaku.com/dark-souls-3-connects-to-its-predecessors-in-some-surpr-1762186354?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://jalopnik.com/the-bugatti-lifestyle-brand-catalog-is-mega-fucking-wei-1762031616?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://lifehacker.com/how-to-answer-tell-me-about-a-time-you-failed-in-an-i-1762148372?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://jalopnik.com/the-bugatti-lifestyle-brand-catalog-is-mega-fucking-wei-1762031616?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM#_ga=1.113457665.767394490.1457373632
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://lifehacker.com/how-to-answer-tell-me-about-a-time-you-failed-in-an-i-1762148372?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM#_ga=1.113457665.767394490.1457373632
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://io9.gizmodo.com/im-terrified-by-the-new-star-trek-series-1762175228?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM#_ga=1.113457665.767394490.1457373632
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://kotaku.com/dark-souls-3-connects-to-its-predecessors-in-some-surpr-1762186354?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM
because it failed test #2 of URL_FILTERS" logger.js:6:7
"omitting http://kotaku.com/dark-souls-3-connects-to-its-predecessors-in-some-surpr-1762186354?utm_source=recirculation&utm_medium=recirculation&utm_campaign=tuesdayPM#_ga=1.113457665.767394490.1457373632
```

**Comment by k88hudson** [comment] 2016-03-07 18:02
Added a note to https://github.com/mozilla/activity-streams/issues/258

**Closed** 2016-03-07 18:02 UTC
Labels: Add-on APIs, Bug

**Comment by pdehaan** [comment] 2016-03-07 18:53
Interesting, I'll retest. Not sure why those URLs would be so long. Maybe we need to reorder the logic and we should be running `sanitizeUrl()` to remove the `utm_*` query string args _before_ checking the URL length. Or whatever, it's a stopgap until we can do POST requests anyways.
