### ISSUE TITLE
ActivityStreams.js points to `resource://` instead of `about:timeline`

### ISSUE THREAD

**Issue by marcoscaceres** [mozilla/activity-streams#117] opened 2016-02-15 01:54 UTC
There is a TODO in the ActivityStreams.js code that states:
```
// TODO: Fix url below to about:timeline when that gets implemented.
```
Adding bug so we don't forget to fix that later...

**Comment by k88hudson** [comment] 2016-02-15 19:53
This is a dupe of https://github.com/mozilla/activity-streams/issues/94

**Closed by k88hudson** 2016-02-15 19:53 UTC
