### ISSUE TITLE
Bug 1262176 - Timestamp is not updated when visiting websites from Activity Stream Timeline page

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#473] opened 2016-04-05 21:36 UTC
via https://bugzilla.mozilla.org/show_bug.cgi?id=1262176

---

Created attachment 8738156 [details]
timestamp is not updated.mp4

#### [Affected versions]:
- Firefox 45.0 and up
- Activity Stream 1.0.7

#### [Affected Platforms]:
- All Windows
- All Mac OS
- All Linux

#### [Prerequisites]:
- Latest Activity Stream add-on version (1.0.7) was previously installed on a profile.
- Multiple pages were previously visited (at least a day old) in order to have items displayed in all areas of both “Timeline” and “New Tab” pages. 

#### [Steps to reproduce]:
1. Start Firefox browser with the profile where Activity Stream add-on was previously installed.
2. Click on "Activity Stream" button from browser toolbar.
3. Click on an item from "Just now" area that was visited yesterday.
4. Click on "Activity Stream" button from browser toolbar.
5. Observe the time for the visited website.

#### [Expected results]:
The timestamp is correctly updated.

#### [Actual results]:
The visited website is moved at the top of the list, marking that was the last item visited but the timestamp is not updated

**Comment by oyiptong** [comment] 2016-04-07 18:15
This is an issue brought on by preview caching. The fix is to not store link metadata, but rather to only store preview data and merge before returning.

**Comment by oyiptong** [comment] 2016-04-07 19:41
closing as duplicate of #468

**Closed by oyiptong** 2016-04-07 19:41 UTC
Labels: Bugzilla
