### ISSUE TITLE
A blue dotted line is displayed between the feed-title and feed-link in "Just now" or "Top Activity" sections

### ISSUE THREAD

**Issue by softvision-VladBacia** [mozilla/activity-streams#257] opened 2016-03-03 09:51 UTC
### Prerequisites:
Have some items in "Just Now" or "Top Activity" sections.

### Steps to reproduce:
1. Right-click on the URL for an item from "Just Now" or "Top Activity" sections.

### Actual results:
URL is highlighted and the context menu is displayed.
There is also displayed a blue dotted line between the feed-title and feed-link. In my opinion this line should not be displayed. 

### Expected results:
URL is highlighted and the context menu is displayed.

![blue dotted line](https://cloud.githubusercontent.com/assets/9248513/13490111/5b14bd7c-e133-11e5-8f6d-717976bf65d3.jpg)

**Comment by pdehaan** [comment] 2016-03-03 23:56
I'm not seeing the outline on right-click (using OS X "El Capitan"), but I do see a stray line if I tab through the elements:

![new_tab](https://cloud.githubusercontent.com/assets/557895/13513740/fef4a7e4-e157-11e5-93a7-947c87400d57.png)
**Figure 1:** Right-clicking a result, no line visible (OS X).

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/13513764/28eedc22-e158-11e5-9320-b988c0eda5c3.png)
**Figure 2:** Stray horizontal line when tabbing through Activity Feed.

---

![new_tab](https://cloud.githubusercontent.com/assets/557895/13513778/46d08ccc-e158-11e5-9e0a-d0e206f74b3b.png)
**Figure 3:** Slight fuzzy outline when tabbing through "Top Sites".

---

I see _zero_ difference between a focused Spotlight result versus a non-focused item.

**Comment by pdehaan** [comment] 2016-04-04 22:11
Unable to reproduce in 1.0.5:

![new_tab](https://cloud.githubusercontent.com/assets/557895/14265636/86f35c52-fa77-11e5-862d-b5773cfc106f.png)

**Comment by pdehaan** [comment] 2016-04-05 22:15
Closing as I can't reproduce this anymore in recent builds.
@softvision-VladBacia Please reopen this if you're still able to see it in 1.0.7+.

**Closed by pdehaan** 2016-04-05 22:15 UTC
Labels: Design feedback needed
