### ISSUE TITLE
Disable Activity Stream/Home navigation element

### ISSUE THREAD

**Issue by pdehaan** [mozilla/activity-streams#399] opened 2016-03-30 01:12 UTC
I think the consensus here was to remove the caret after "Activity Stream" and remove the Home link here, but keep the header.

![screenshot_3_29_16__6_10_pm](https://cloud.githubusercontent.com/assets/557895/14128872/9ecd1fae-f5d9-11e5-9489-9707d3c337b8.png)

**Comment by k88hudson** [comment] 2016-03-30 21:56
Dupe of #422

**Closed by k88hudson** 2016-03-30 21:56 UTC
Labels: Design feedback needed
