### ISSUE TITLE
Better error/empty/loading states

### ISSUE THREAD

**Issue by k88hudson** [mozilla/activity-streams#81] opened 2016-02-10 19:45 UTC
We need a first pass at what happens when each component is empty/loading/an error happens.

We should *definitely* have a nice experience for a blank profile (i.e. no history, bookmarks)

This will need some design input.

**Comment by k88hudson** [comment] 2016-02-22 16:21
So far, we've landed some dashed boxes if nothing exists, which is better than nothing.

@nchapman did you want to come up with some "placeholder" content for blank profiles/cleared history?

**Comment by nchapman** [comment] 2016-02-29 23:04
Duplicate of #200.

**Closed by nchapman** 2016-02-29 23:04 UTC
Labels: Design feedback needed
